name: Build and Quality Checks

on:
  push:
    tags: [ 'v*' ]
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Required for SonarCloud analysis
    
    - name: Set up JDK 8 for Building
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    
    - name: Check code style
      run: mvn checkstyle:check
    
    - name: Run unit tests with coverage
      run: mvn verify
    
    - name: Run mutation tests
      run: mvn org.pitest:pitest-maven:mutationCoverage
    
    - name: Set up JDK 11 for SonarCloud
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: SonarCloud Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar -Dsonar.projectKey=kedmison_hive-hdr-udaf -Dsonar.organization=kedmison
    
    - name: Restore JDK 8 for remaining steps
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
    
    - name: Run SpotBugs
      run: mvn spotbugs:check
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: target/*.jar
        generate_release_notes: true
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        body_path: CHANGELOG.md  # Include changelog in release notes
